# Generated by Django 6.0.4 on 2026-04-13 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('technical', 'Technical Event'), ('workshop', 'Workshop'), ('ctf', 'Capture The Flag')], default='technical', max_length=20)),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2')], default=1)),
                ('duration_hours', models.IntegerField(default=3)),
                ('team_size_min', models.IntegerField(default=1)),
                ('team_size_max', models.IntegerField(default=1)),
                ('fee_ieee_member', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_non_ieee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_per_team', models.BooleanField(default=True, help_text='True if fee is per team, False if per participant')),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_teams', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='registration.event')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('college_name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=200)),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1)),
                ('is_ieee_member', models.BooleanField(default=False)),
                ('ieee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_team_leader', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='PayPal payment/order ID', max_length=200, null=True)),
                ('payment_payer_id', models.CharField(blank=True, help_text='PayPal payer ID', max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='e.g. paypal, manual', max_length=50, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registration.event')),
                ('user', models.ForeignKey(blank=True, help_text='The portal user account that created this registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='registration.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
